added support for daemon service wrapper

diff --git a/debian/webclient.initd b/debian/webclient.initd
--- a/debian/webclient.initd
+++ b/debian/webclient.initd
@@ -10,12 +10,7 @@
 # Description:            Start/Stop the HSN2 WebClient daemon.
 ### END INIT INFO
 
-if [ -z "`which java`" ]; then
-	echo "JAVA need to be installed first!"
-	exit 1
-fi
 
-. /lib/lsb/init-functions
 
 NAME="HSN2 WebClient"
 HSN2_COMPONENT="webclient"
@@ -25,17 +20,63 @@ PIDFILE="/var/run/hsn2-$HSN2_COMPONENT.pid"
 
 HSN2_COMPONENT_PARAMS="--connector 127.0.0.1 \
 --dataStore http://localhost:8080 \
---maxThreads 4"
+--maxThreads 5"
 
 HSN2_JVM_PARAMS="-Xmx1500m -Xms1500m -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.port=1101"
 
-case "$1" in
+#HSN2_JVM_PARAMS="-Xmx80m -Xms80m -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.port=1101"
+#HSN2_JVM_PARAMS="$HSN2_JVM_PARAMS -Xloggc:${HSN2_COMPONENT_HOME}/${HSN2_COMPONENT}.GC.log"
+
+
+
+. /lib/lsb/init-functions
+
+if [ -z "`which java`" ]; then
+	log_failure_msg "Error" "JAVA need to be installed first."
+	exit 1
+fi
+
+JAVA_HOME="/usr/lib/jvm/java-7-openjdk-amd64"
+
+JSVCBIN=`which jsvc`
+
+MAINCLASS="pl.nask.hsn2.service.WebClientService"
+
+use_jsvc_wrapper () {
+	log_daemon_msg "using jsvc..."
+	case "$1" in
+		start)
+			log_daemon_msg "Starting" "$NAME"
+
+			$JSVCBIN -home $JAVA_HOME -wait 30 -pidfile ${PIDFILE} $HSN2_JVM_PARAMS -cp $HSN2_COMPONENT_HOME/hsn2-$HSN2_COMPONENT.jar $MAINCLASS $HSN2_COMPONENT_PARAMS
+			log_end_msg $?
+			return $?
+			;;
+		stop)
+			log_daemon_msg "Stopping" "$NAME"
+			$JSVCBIN -home $JAVA_HOME -stop -pidfile ${PIDFILE} $HSN2_JVM_PARAMS -cp $HSN2_COMPONENT_HOME/hsn2-$HSN2_COMPONENT.jar $MAINCLASS 
+
+			log_end_msg $?
+			return $?
+			;;
+		status)
+			status_of_proc -p $PIDFILE $JSVCBIN $NAME && exit 0 || exit $?
+			;;
+	esac
+		
+return 0
+}
+
+
+use_start_stop_daemon() {
+	log_daemon_msg "using start-stop-daemon..."
+	case "$1" in
 	start)
 		log_daemon_msg "Starting" "$NAME"
 		cd "$HSN2_COMPONENT_HOME"
 		# workaround (see redmine #6587, #6324)
 		start-stop-daemon --start --quiet --oknodo --background --make-pidfile --pidfile $PIDFILE --exec /usr/bin/java -- $HSN2_JVM_PARAMS -jar $HSN2_COMPONENT_HOME/hsn2-$HSN2_COMPONENT.jar $HSN2_COMPONENT_PARAMS
-		sleep 1
+		sleep 5
 		PID=`cat $PIDFILE`
 		TEST=`ps ax | grep $PID | grep java | sed -e 's/^ *//' | cut -d' ' -f1`
 		if [ -n "$TEST" ]; then
@@ -62,5 +103,16 @@ case "$1" in
 	status)
 		status_of_proc -p $PIDFILE "$JAVA" "$NAME" && exit 0 || exit $?
 		;;
-esac
-exit 0
+	esac
+return 0
+
+}
+	
+if [ -z "$JSVCBIN"  -o -z "$JAVA_HOME" ]; then
+	use_start_stop_daemon $@
+else
+	use_jsvc_wrapper $@
+fi
+
+exit $?
+
